site:
    title: TupiLabs
    description: Innovation and Open Source
    author: TupiLabs
    pretty_urls: true
    enable_gzip: true
    debug: true
    
smartypants:
    enable: true

server:
    config_variants: 
        default:
            site: 
                base_url: http://localhost/tupilabs.com/
        live: 
            site: 
                base_url: http://localhost:8080/

baker:
    skip_patterns:
        - /^index.php/
    config_variants:
        default:
            site:
                base_url: http://localhost/tupilabs.com/blog/
        production: 
            site: 
                base_url: http://www.tupilabs.com/